## 2.2.1 入門
https://pytorch.apachecn.org/docs/1.4/blitz/tensor_tutorial.html

#### PyTorch是一个基于python的科学计算包，主要针对两类人群：

* 作为NumPy的替代品，可以利用GPU的性能进行计算
* 作为一个高灵活性、速度快的深度学习平台


#### 张量

- Tensor(张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.5461e-01, 4.4377e+27, 1.7975e+19],
        [4.6894e+27, 7.9463e+08, 3.2604e-12],
        [2.6209e+20, 4.1641e+12, 1.9434e-19],
        [3.0881e+29, 6.3828e+28, 1.4603e-19],
        [7.7179e+28, 7.7591e+26, 3.0357e+32]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7822, 0.9431, 0.0810],
        [0.3029, 0.0426, 0.5275],
        [0.6488, 0.5418, 0.4708],
        [0.9403, 0.0479, 0.9721],
        [0.7419, 0.8879, 0.0893]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6260, 0.1439, 0.6438],
        [0.7722, 0.3298, 0.1748],
        [0.0134, 0.8069, 0.0499],
        [0.5798, 0.5388, 0.2715],
        [0.5384, 0.6668, 0.3562]])


In [8]:
torch.add(x, y)

tensor([[0.6260, 0.1439, 0.6438],
        [0.7722, 0.3298, 0.1748],
        [0.0134, 0.8069, 0.0499],
        [0.5798, 0.5388, 0.2715],
        [0.5384, 0.6668, 0.3562]])

In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6260, 0.1439, 0.6438],
        [0.7722, 0.3298, 0.1748],
        [0.0134, 0.8069, 0.0499],
        [0.5798, 0.5388, 0.2715],
        [0.5384, 0.6668, 0.3562]])


In [10]:
y.add(x)

tensor([[0.6260, 0.1439, 0.6438],
        [0.7722, 0.3298, 0.1748],
        [0.0134, 0.8069, 0.0499],
        [0.5798, 0.5388, 0.2715],
        [0.5384, 0.6668, 0.3562]])

#### 注意：

    任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x。
    但x.add(y) 和 x.t()會回傳一個新的tensor


#### 改变形状：如果想改变形状，可以使用torch.view

In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### 如果是仅包含一个元素的tensor，可以使用.item()来得到对应的python数值

In [20]:
x = torch.randn(1)
x.item()


-0.6396402716636658

In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b= a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [27]:
a.add_(1)

tensor([4., 4., 4., 4., 4.])

In [28]:
b

array([4., 4., 4., 4., 4.], dtype=float32)

In [34]:
import numpy as np
a = np.ones(5)

b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### CUDA上的张量
- 张量可以使用.to方法移动到任何设备(device）上：

In [35]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([0.3604], device='cuda:0')
tensor([0.3604], dtype=torch.float64)


## 2.2.2 Autograd
https://pytorch.apachecn.org/docs/1.4/blitz/autograd_tutorial.html


In [9]:
import torch

In [10]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
y.grad_fn

In [13]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [14]:
out.backward()

In [15]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [16]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.7792,  0.6360, -0.5498], requires_grad=True)

In [17]:
y = x * 2
y

tensor([ 1.5583,  1.2721, -1.0996], grad_fn=<MulBackward0>)

In [18]:
y = y * 2
y

tensor([ 3.1167,  2.5442, -2.1993], grad_fn=<MulBackward0>)

https://stackoverflow.com/questions/50753477/what-does-data-norm-1000-do-in-pytorch

y.data.norm()
=> torch.sqrt(torch.sum(torch.pow(y, 2))) 

norm() => L2 or Euclidean norm.

In [19]:
while y.data.norm() < 1000:  
    y = y * 2  # 持續累加計算，直到y向量的的歐基里得大小(至起點的距離) / l2 Norm 超過1000

print(y)

tensor([ 797.8687,  651.3074, -563.0103], grad_fn=<MulBackward0>)


## 2.2.3 神經網路

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 输入图像channel：1；输出channel：6；5x5卷积核
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # 2x2 Max pooling
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # 如果是方阵,则可以只使用一个数字进行定义
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # 除去批处理维度的其他所有维度
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


In [3]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0029, -0.0516, -0.0460, -0.1267,  0.0574, -0.0506, -0.0227, -0.0817,
         -0.0440,  0.0098]], grad_fn=<AddmmBackward>)


In [4]:
net.zero_grad()
out.backward(torch.randn(1, 10))